import type { JobHandle, JobHandlers, JobSpec } from './types.js'

/**
 * The built-in "demo" provider: a simulated agent that streams a few tool events and
 * writes a plausible Markdown deliverable derived from the prompt, without calling any
 * model. It exists so the product can be tried end to end before any CLI is installed.
 */

type Kind = 'plan' | 'implement' | 'review' | 'test' | 'research' | 'generic'

const hasCjk = (s: string) => /[\u4e00-\u9fff]/.test(s)

const detectKind = (text: string): Kind => {
  const p = text.toLowerCase()
  if (/(评审|审查|review|audit)/.test(p)) return 'review'
  if (/(测试|test)/.test(p)) return 'test'
  if (/(方案|设计|架构|规划|plan|design|architect)/.test(p)) return 'plan'
  if (/(实现|修复|开发|重构|implement|fix|build|refactor|add )/.test(p)) return 'implement'
  if (/(调研|研究|报告|总结|research|report|summar)/.test(p)) return 'research'
  return 'generic'
}

/** The task part of the prompt (between the role block and the "Expected output" block). */
const taskOf = (prompt: string): { title: string; body: string; upstreamChars: number } => {
  // the server joins role / prompt / expected output with blank-line separated "---" markers;
  // upstream Markdown pasted into the prompt may contain its own "---" lines, so match exactly
  const blocks = prompt.split(/\n\n---\n\n/)
  const body = (blocks.length >= 2 ? blocks[1] : blocks[0]).trim()
  const firstLine = body.split('\n').map((l) => l.trim()).find((l) => l && !/^[#>*-]/.test(l)) ?? body.slice(0, 80)
  const title = firstLine.replace(/[:：。.!！?？]\s*$/, '').slice(0, 80)
  return { title, body, upstreamChars: Math.max(0, body.length - firstLine.length) }
}

const slugOf = (title: string) => title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 24) || 'feature'

// deterministic pseudo-random delays (seeded by the job id) so demo runs look alive but reproducible
const seeded = (seed: string) => {
  let h = 2166136261
  for (const c of seed) h = Math.imul(h ^ c.charCodeAt(0), 16777619)
  return () => {
    h = Math.imul(h ^ (h >>> 15), 2246822507)
    h = Math.imul(h ^ (h >>> 13), 3266489909)
    return ((h ^= h >>> 16) >>> 0) / 4294967296
  }
}

const EVENTS: Record<Kind, Array<[string, string]>> = {
  plan: [
    ['🔧 Read README.md', '🔧 Read README.md'],
    ['🔧 Glob src/**/*.ts', '🔧 Glob src/**/*.ts'],
    ['🔧 Read package.json', '🔧 Read package.json'],
    ['💬 正在梳理模块边界与需要改动的文件…', '💬 Mapping module boundaries and the files to change…'],
  ],
  implement: [
    ['🔧 Read src/index.ts', '🔧 Read src/index.ts'],
    ['🔧 Grep "TODO" src', '🔧 Grep "TODO" src'],
    ['✏️ Edit src/{slug}.ts', '✏️ Edit src/{slug}.ts'],
    ['🔧 Bash npm test', '🔧 Bash npm test'],
    ['💬 测试通过，整理改动摘要。', '💬 Tests pass; summarising the change.'],
  ],
  review: [
    ['🔧 Bash git diff --stat', '🔧 Bash git diff --stat'],
    ['🔧 Read src/{slug}.ts', '🔧 Read src/{slug}.ts'],
    ['💬 检查错误处理与边界条件…', '💬 Checking error handling and edge cases…'],
    ['🔧 Grep "catch" src', '🔧 Grep "catch" src'],
  ],
  test: [
    ['🔧 Bash npm test', '🔧 Bash npm test'],
    ['✏️ Write test/{slug}.test.ts', '✏️ Write test/{slug}.test.ts'],
    ['🔧 Bash npm test', '🔧 Bash npm test'],
    ['💬 全部通过。', '💬 All green.'],
  ],
  research: [
    ['🔧 WebSearch "{title}"', '🔧 WebSearch "{title}"'],
    ['🔧 WebFetch (3 sources)', '🔧 WebFetch (3 sources)'],
    ['💬 交叉比对来源，提炼结论…', '💬 Cross-checking sources and distilling findings…'],
  ],
  generic: [
    ['🔧 Read README.md', '🔧 Read README.md'],
    ['💬 思考中…', '💬 Thinking…'],
  ],
}

const output = (kind: Kind, title: string, zh: boolean, upstreamChars: number): string => {
  const slug = slugOf(title)
  const upstream = upstreamChars > 200 ? (zh ? `\n\n> 已参考上游步骤的输出（${upstreamChars} 字）。` : `\n\n> Built on the upstream output (${upstreamChars} chars).`) : ''
  const footer = zh ? '\n\n---\n_演示 Agent 生成：没有调用任何模型。把 Agent 的 CLI 换成 Claude Code / Codex / Gemini 即可得到真实结果。_' : '\n\n---\n_Generated by the demo agent: no model was called. Switch the agent to Claude Code / Codex / Gemini for real results._'
  const body: Record<Kind, [string, string]> = {
    plan: [
      `## 技术方案：${title}\n\n### 改动清单\n1. \`src/api/${slug}.ts\` — 新增接口与参数校验\n2. \`src/services/${slug}.ts\` — 核心逻辑（含错误处理与日志）\n3. \`test/${slug}.test.ts\` — 单元测试\n\n### 接口\n- \`POST /api/${slug}\` → \`{ ok: true, id }\`\n\n### 风险与对策\n- 与现有模块的兼容性：先加功能开关，再逐步启用。\n- 数据迁移：提供回滚脚本。`,
      `## Design: ${title}\n\n### Files to change\n1. \`src/api/${slug}.ts\` — new endpoint and input validation\n2. \`src/services/${slug}.ts\` — core logic (error handling, logging)\n3. \`test/${slug}.test.ts\` — unit tests\n\n### Interface\n- \`POST /api/${slug}\` → \`{ ok: true, id }\`\n\n### Risks\n- Compatibility with existing modules: ship behind a flag, enable gradually.\n- Data migration: include a rollback script.`,
    ],
    implement: [
      `## 改动摘要：${title}\n\n- 新增 \`src/${slug}.ts\`（+42 行）\n- 修改 \`src/index.ts\`：注册新模块\n- 新增测试 \`test/${slug}.test.ts\`（3 个用例）\n\n### 测试\n\`\`\`\nnpm test\n✓ 12 passed\n\`\`\`\n\n### 说明\n改动保持最小，没有触碰无关文件。`,
      `## Change summary: ${title}\n\n- Added \`src/${slug}.ts\` (+42 lines)\n- Updated \`src/index.ts\` to register the module\n- Added \`test/${slug}.test.ts\` (3 cases)\n\n### Tests\n\`\`\`\nnpm test\n✓ 12 passed\n\`\`\`\n\n### Notes\nMinimal change; unrelated files untouched.`,
    ],
    review: [
      `## 评审报告：${title}\n\n**结论：通过（有 2 条建议）**\n\n### 问题\n1. \`src/${slug}.ts:27\` — 输入未做长度限制，建议加上上限。\n2. 缺少失败路径的测试用例。\n\n### 做得好的\n- 接口命名与现有风格一致\n- 错误信息清晰`,
      `## Review: ${title}\n\n**Verdict: approve (2 suggestions)**\n\n### Findings\n1. \`src/${slug}.ts:27\` — input has no length limit; add an upper bound.\n2. No test covers the failure path.\n\n### Good\n- Naming matches the existing style\n- Error messages are clear`,
    ],
    test: [
      `## 测试报告：${title}\n\n| 套件 | 用例 | 结果 |\n|---|---|---|\n| ${slug} | 3 | ✓ |\n| regression | 9 | ✓ |\n\n新增用例覆盖：正常路径、空输入、并发调用。`,
      `## Test report: ${title}\n\n| Suite | Cases | Result |\n|---|---|---|\n| ${slug} | 3 | ✓ |\n| regression | 9 | ✓ |\n\nNew cases cover the happy path, empty input and concurrent calls.`,
    ],
    research: [
      `## 调研摘要：${title}\n\n### 结论\n主流做法有两种；对本项目而言方案 A 更简单，方案 B 更可扩展。\n\n### 依据\n- 来源 1：官方文档\n- 来源 2：社区高赞实现\n- 来源 3：近期讨论\n\n### 建议\n先用方案 A 落地，预留切换到 B 的接口。`,
      `## Research summary: ${title}\n\n### Conclusion\nTwo mainstream approaches; A is simpler for this project, B scales further.\n\n### Evidence\n- Source 1: official docs\n- Source 2: a widely used community implementation\n- Source 3: recent discussion\n\n### Recommendation\nShip A now and keep an interface to move to B.`,
    ],
    generic: [`## ${title}\n\n已完成。要点：\n- 步骤 1\n- 步骤 2\n- 步骤 3`, `## ${title}\n\nDone. Key points:\n- Step 1\n- Step 2\n- Step 3`],
  }
  return body[kind][zh ? 0 : 1] + upstream + footer
}

export function runDemoJob(job: JobSpec, handlers: JobHandlers): JobHandle {
  const timers: NodeJS.Timeout[] = []
  let finished = false
  const done = (result: Parameters<JobHandlers['onDone']>[0]) => {
    if (finished) return
    finished = true
    for (const t of timers) clearTimeout(t)
    handlers.onDone(result)
  }
  const { title, body, upstreamChars } = taskOf(job.stdin)
  // answer in the language of the task itself, not of whatever upstream output was pasted in
  const zh = /[A-Za-z\u4e00-\u9fff]/.test(title) ? hasCjk(title) : hasCjk(body)
  const kind = detectKind(body || job.stdin)
  const rnd = seeded(job.id)
  const slug = slugOf(title)

  handlers.onLog('system', zh ? 'demo agent · 未调用任何模型，输出为本地生成' : 'demo agent · no model is called, the output is generated locally')
  let at = 200
  for (const [zhLine, enLine] of EVENTS[kind]) {
    at += 300 + Math.floor(rnd() * 600)
    const line = (zh ? zhLine : enLine).replace('{slug}', slug).replace('{title}', title.slice(0, 40))
    timers.push(setTimeout(() => handlers.onLog('event', line), at))
  }
  at += 400 + Math.floor(rnd() * 500)
  timers.push(
    setTimeout(() => {
      handlers.onLog('event', zh ? '✓ result · demo' : '✓ result · demo')
      done({ exitCode: 0, output: output(kind, title, zh, upstreamChars) })
    }, at),
  )
  return {
    cancel: () => done({ exitCode: null, output: '', error: 'cancelled', cancelled: true }),
  }
}
